lifecycle_manager_main:
  ros__parameters:
    autostart: true
    node_names: ["/costmap_node_manager"]
    use_sim_time: true

pointcloud_to_laserscan:
  ros__parameters:
    transform_tolerance: 0.01
    min_height: 0.0
    max_height: 100.0
    angle_min: -1.5708  # -M_PI/2
    angle_max: 1.5708  # M_PI/2
    angle_increment: 0.0087  # M_PI/360.0
    scan_time: 0.3333
    range_min: 0.45
    range_max: 100.0
    use_inf: true
    inf_epsilon: 1.0

